/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Doador;
import javax.swing.JOptionPane;

/**
 *
 * @author leo_m
 */
public class TelaAvisos extends javax.swing.JFrame {

    /**
     * Creates new form TelaDoacoes
     */
    public TelaAvisos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGAnemia = new javax.swing.ButtonGroup();
        Sim1 = new javax.swing.JRadioButton();
        Nao1 = new javax.swing.JRadioButton();
        lbConcorda = new javax.swing.JLabel();
        lbTermo = new javax.swing.JLabel();
        lbTexto1 = new javax.swing.JLabel();
        lbTexto2 = new javax.swing.JLabel();
        lbTexto3 = new javax.swing.JLabel();
        lbTexto4 = new javax.swing.JLabel();
        lbTexto5 = new javax.swing.JLabel();
        lbTexto6 = new javax.swing.JLabel();
        btnAvancar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGAnemia.add(Sim1);
        Sim1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Sim1.setText("Sim");
        Sim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sim1ActionPerformed(evt);
            }
        });

        btnGAnemia.add(Nao1);
        Nao1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Nao1.setText("Não");

        lbConcorda.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbConcorda.setText("Você concorda?");

        lbTermo.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbTermo.setText("Termos para doação");

        lbTexto1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbTexto1.setText("* Serão coletados aproximadamente 450ml de sangue em uma bolsa de uso único");

        lbTexto2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbTexto2.setText("e estéril, sendo, portanto, a coleta de sangue totalmente segura.");

        lbTexto3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbTexto3.setText("* São realizados diversos testes do sangue, cujos resultados serão armazenados");

        lbTexto4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbTexto4.setText("em nossos bancos de dados.");

        lbTexto5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbTexto5.setText("* Algumas perguntas pessoais serão realizadas para que a saúde do doador e a ");

        lbTexto6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbTexto6.setText("do receptor não seja comprometida.");

        btnAvancar.setText("AVANÇAR");
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbTermo)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAvancar)
                        .addGap(239, 239, 239))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTexto5)
                            .addComponent(lbTexto1)
                            .addComponent(lbTexto3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTexto6)
                                    .addComponent(lbTexto2)
                                    .addComponent(lbTexto4))))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Sim1)
                                .addGap(18, 18, 18)
                                .addComponent(Nao1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lbConcorda)
                                .addGap(3, 3, 3)))
                        .addGap(224, 224, 224))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTermo)
                .addGap(28, 28, 28)
                .addComponent(lbTexto1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTexto2)
                .addGap(18, 18, 18)
                .addComponent(lbTexto3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTexto4)
                .addGap(18, 18, 18)
                .addComponent(lbTexto5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTexto6)
                .addGap(18, 18, 18)
                .addComponent(lbConcorda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sim1)
                    .addComponent(Nao1))
                .addGap(18, 18, 18)
                .addComponent(btnAvancar)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sim1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sim1ActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed
        if (!Nao1.isSelected() && !Sim1.isSelected()) {
            JOptionPane.showMessageDialog(null, "Selecione se concorda ou não!");
        } else if (Sim1.isSelected()) {
            dispose();
            TelaPerguntas tp = new TelaPerguntas();
            tp.setDoador(doador);

            tp.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Você não pode doar se não concordar.");
            dispose();
            TelaInicial ti = new TelaInicial();
            ti.setVisible(true);
        }
    }//GEN-LAST:event_btnAvancarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAvisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAvisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAvisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAvisos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaAvisos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Nao1;
    private javax.swing.JRadioButton Sim1;
    private javax.swing.JButton btnAvancar;
    private javax.swing.ButtonGroup btnGAnemia;
    private javax.swing.JLabel lbConcorda;
    private javax.swing.JLabel lbTermo;
    private javax.swing.JLabel lbTexto1;
    private javax.swing.JLabel lbTexto2;
    private javax.swing.JLabel lbTexto3;
    private javax.swing.JLabel lbTexto4;
    private javax.swing.JLabel lbTexto5;
    private javax.swing.JLabel lbTexto6;
    // End of variables declaration//GEN-END:variables
    private Doador doador;

    /**
     * @return the doador
     */
    public Doador getDoador() {
        return doador;
    }

    /**
     * @param doador the doador to set
     */
    public void setDoador(Doador doador) {
        this.doador = doador;
    }
}
