/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Doador;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import model.CorrigeData;
import model.Querys;
import model.ValidaCPF;

/**
 *
 * @author leo_m
 */
public class TelaCadastro extends javax.swing.JFrame {

    private void erroDados() {
        String erro = "Preencha ";

        switch (this.erroCamp) {
            case 1:
                erro += "o nome.";
                break;
            case 2:
                erro += "o cpf.";
                break;
            case 3:
                erro += "a data de nascimento.";
                break;
            case 4:
                erro += "o nome da mãe.";
                break;
            case 5:
                erro += "o nome do pai.";
                break;
            case 6:
                erro += "o endereço.";
                break;
            case 7:
                erro += "o número.";
                break;
            case 8:
                erro += "o bairro.";
                break;
            case 10:
                erro += "o sexo.";
                break;
        }
        JOptionPane.showMessageDialog(null, erro);

    }

    private boolean verificaDados() {
        ValidaCPF vcpf = new ValidaCPF();
        if (tfNomeCompleto.getText() == null || tfNomeCompleto.getText().trim().equals("")) {
            erroCamp = 1;
            return false;
        } else if (tfNumeroDoc.getText() == null || tfNumeroDoc.getText().trim().equals("") || !vcpf.isCPF(tfNumeroDoc.getText())) {
            erroCamp = 2;
            return false;
        } else if (tfDataNascimento.getText() == null || tfDataNascimento.getText().trim().equals("")) {
            erroCamp = 3;
            return false;
        } else if (tfNomeMae.getText() == null || tfNomeMae.getText().trim().equals("")) {
            erroCamp = 4;
            return false;
        } else if (tfNomePai.getText() == null || tfNomePai.getText().trim().equals("")) {
            erroCamp = 5;
            return false;
        } else if (tfEndereco.getText() == null || tfEndereco.getText().trim().equals("")) {
            erroCamp = 6;
            return false;
        } else if (tfNumero.getText() == null || tfNumero.getText().trim().equals("")) {
            erroCamp = 7;
            return false;
        } else if (tfBairro.getText() == null || tfBairro.getText().trim().equals("")) {
            erroCamp = 8;
            return false;
        } else if (!rbtnFem.isSelected() && !rbtnMasc.isSelected()) {
            erroCamp = 10;
            return false;
        }
        erroCamp = 0;
        return true;
    }

    private void cadastro() throws SQLException {

        if (verificaDados()) {
            this.doador = new Doador();
            CorrigeData cd = new CorrigeData();
            Querys qr = new Querys();
            doador.setNomeCompleto(tfNomeCompleto.getText());
            doador.setNomeMae(tfNomeMae.getText());
            doador.setNomePai(tfNomePai.getText());
            doador.setDocumento(tfNumeroDoc.getText());
            doador.setNumero(Integer.parseInt(tfNumero.getText()));
            doador.setEndereco(tfEndereco.getText());
            doador.setBairro(tfBairro.getText());
            doador.setComplemento(tfComplemento.getText());
            doador.setDataNascimento(cd.correcao(tfDataNascimento.getText()));
            if (rbtnMasc.isSelected()) {
                doador.setSexo("M");
            } else {
                doador.setSexo("F");
            }
            if (qr.novoDoador(doador)) {
                JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!");
                dispose();
                TelaAvisos ta = new TelaAvisos();
                ta.setVisible(true);
                ta.setDoador(doador);
            } else {
                JOptionPane.showMessageDialog(null, "Cadastro não realizado!");
            }
        } else {
            erroDados();
        }
    }

    /**
     * Creates new form telaCadastro
     */
    public TelaCadastro() {
        initComponents();

//        tfNumeroDoc.setText(doador.getDocumento());
    }
//02256276805

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbCadastroDoador = new javax.swing.JLabel();
        lbBancoSangue = new javax.swing.JLabel();
        lbNomeCompleto = new javax.swing.JLabel();
        lbDataNascimento = new javax.swing.JLabel();
        lbNomeMae = new javax.swing.JLabel();
        lbNumeroDoc = new javax.swing.JLabel();
        lbNomePai = new javax.swing.JLabel();
        lbNumero = new javax.swing.JLabel();
        lbComplemento = new javax.swing.JLabel();
        lbBairro = new javax.swing.JLabel();
        lbEndereco = new javax.swing.JLabel();
        tfNomeCompleto = new javax.swing.JTextField();
        tfNomeMae = new javax.swing.JTextField();
        tfNomePai = new javax.swing.JTextField();
        tfEndereco = new javax.swing.JTextField();
        tfNumero = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        tfComplemento = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        tfNumeroDoc = new javax.swing.JFormattedTextField();
        tfDataNascimento = new javax.swing.JFormattedTextField();
        lbSexo = new javax.swing.JLabel();
        rbtnMasc = new javax.swing.JRadioButton();
        rbtnFem = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbCadastroDoador.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbCadastroDoador.setForeground(new java.awt.Color(0, 5, 70));
        lbCadastroDoador.setText("CADASTRO DE DOADOR");

        lbBancoSangue.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbBancoSangue.setForeground(new java.awt.Color(128, 0, 0));
        lbBancoSangue.setText("Banco de Sangue");

        lbNomeCompleto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbNomeCompleto.setForeground(new java.awt.Color(0, 5, 70));
        lbNomeCompleto.setText("Nome Completo");

        lbDataNascimento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbDataNascimento.setForeground(new java.awt.Color(0, 5, 70));
        lbDataNascimento.setText("Data de Nascimento");
        lbDataNascimento.setToolTipText("");

        lbNomeMae.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbNomeMae.setForeground(new java.awt.Color(0, 5, 70));
        lbNomeMae.setText("Nome da Mãe");

        lbNumeroDoc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbNumeroDoc.setForeground(new java.awt.Color(0, 5, 70));
        lbNumeroDoc.setText("Número do CPF");

        lbNomePai.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbNomePai.setForeground(new java.awt.Color(0, 5, 70));
        lbNomePai.setText("Nome do Pai");

        lbNumero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbNumero.setForeground(new java.awt.Color(0, 5, 70));
        lbNumero.setText("Número");

        lbComplemento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbComplemento.setForeground(new java.awt.Color(0, 5, 70));
        lbComplemento.setText("Complemento");

        lbBairro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbBairro.setForeground(new java.awt.Color(0, 5, 70));
        lbBairro.setText("Bairro");

        lbEndereco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbEndereco.setForeground(new java.awt.Color(0, 5, 70));
        lbEndereco.setText("Endereço");

        btnCadastrar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(128, 0, 0));
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        try {
            tfNumeroDoc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDataNascimentoActionPerformed(evt);
            }
        });

        lbSexo.setForeground(new java.awt.Color(0, 5, 70));
        lbSexo.setText("Sexo");

        btnGSexo.add(rbtnMasc);
        rbtnMasc.setText("M");
        rbtnMasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMascActionPerformed(evt);
            }
        });

        btnGSexo.add(rbtnFem);
        rbtnFem.setText("F");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbCadastroDoador)
                        .addGap(173, 173, 173))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNomePai)
                                    .addComponent(lbEndereco)
                                    .addComponent(lbBairro)
                                    .addComponent(lbNomeMae))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfNomeMae)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(tfBairro)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lbComplemento)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lbNumero)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfNomePai))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tfNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbBancoSangue)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNomeCompleto)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbNumeroDoc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfNumeroDoc)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbDataNascimento)))
                                .addGap(10, 10, 10)
                                .addComponent(tfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbSexo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtnMasc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnFem)
                                .addGap(21, 21, 21)))))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCadastrar)
                .addGap(265, 265, 265))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbBancoSangue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(lbCadastroDoador)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeCompleto)
                    .addComponent(tfNomeCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNumeroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDataNascimento)
                    .addComponent(tfNumeroDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSexo)
                    .addComponent(rbtnMasc)
                    .addComponent(rbtnFem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeMae)
                    .addComponent(tfNomeMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomePai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNomePai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNumero)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbEndereco)
                        .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBairro)
                    .addComponent(lbComplemento)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnCadastrar)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        try {
            cadastro();
        } catch (SQLException ex) {
            Logger.getLogger(TelaCadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void rbtnMascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnMascActionPerformed

    private void tfDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDataNascimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.ButtonGroup btnGSexo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbBancoSangue;
    private javax.swing.JLabel lbCadastroDoador;
    private javax.swing.JLabel lbComplemento;
    private javax.swing.JLabel lbDataNascimento;
    private javax.swing.JLabel lbEndereco;
    private javax.swing.JLabel lbNomeCompleto;
    private javax.swing.JLabel lbNomeMae;
    private javax.swing.JLabel lbNomePai;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbNumeroDoc;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JRadioButton rbtnFem;
    private javax.swing.JRadioButton rbtnMasc;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JFormattedTextField tfDataNascimento;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNomeCompleto;
    private javax.swing.JTextField tfNomeMae;
    private javax.swing.JTextField tfNomePai;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JFormattedTextField tfNumeroDoc;
    // End of variables declaration//GEN-END:variables
    private Doador doador;
    private int erroCamp;

    /**
     * @return the doador
     */
    public Doador getDoador() {
        return doador;
    }

    /**
     * @param doador the doador to set
     */
    public void setDoador(Doador doador) {
        this.doador = doador;
    }

}
